// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJx8so1Ob4sIlDqKTEnv5kRTjSVL1pQuI',
    appId: '1:60237715262:web:8e5082e33e4789f0aabe6f',
    messagingSenderId: '60237715262',
    projectId: 'fir-flutter-test-3c594',
    authDomain: 'fir-flutter-test-3c594.firebaseapp.com',
    storageBucket: 'fir-flutter-test-3c594.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5okxJSP4Lh24p8-hcXwqr6tVNcMniJXc',
    appId: '1:60237715262:android:fe45f4e5fd98bc03aabe6f',
    messagingSenderId: '60237715262',
    projectId: 'fir-flutter-test-3c594',
    storageBucket: 'fir-flutter-test-3c594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8Qszrx55ddJIVtdvn-6dHfMvbTFuJLs',
    appId: '1:60237715262:ios:bf84b18e089577f7aabe6f',
    messagingSenderId: '60237715262',
    projectId: 'fir-flutter-test-3c594',
    storageBucket: 'fir-flutter-test-3c594.appspot.com',
    iosClientId: '60237715262-asvcql7dofqrqch28908fiu8vq2shhff.apps.googleusercontent.com',
    iosBundleId: 'com.example.parollaGameMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8Qszrx55ddJIVtdvn-6dHfMvbTFuJLs',
    appId: '1:60237715262:ios:bf84b18e089577f7aabe6f',
    messagingSenderId: '60237715262',
    projectId: 'fir-flutter-test-3c594',
    storageBucket: 'fir-flutter-test-3c594.appspot.com',
    iosClientId: '60237715262-asvcql7dofqrqch28908fiu8vq2shhff.apps.googleusercontent.com',
    iosBundleId: 'com.example.parollaGameMvvm',
  );
}
